### PR TITLE
re-export serde error

### LINKED ISSUE #240: Re-expose serde_json::error::Error
Right now I have to add `serde_json` as a dependency to my project just to wrap the `serde_json::error::Error` error returned by `GeoJson::from_reader` into my own error. It would be convenient if that error type were exposed in the public interface, similarly to what was done in #185.

### PR DESCRIPTION
**Pull request by michaelkirk**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

Fixes https://github.com/georust/geojson/issues/240

We are already re-exporting some serde objects, so this doesn't create a new semver contract that wasn't already there.

And this way downstream users can interact with the error type without having to explicitly install serde_json.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -453,3 +453,4 @@ pub use conversion::quick_collection;
 
 pub type JsonValue = serde_json::Value;
 pub type JsonObject = serde_json::Map<String, JsonValue>;
+pub type MalformedGeoJsonError = serde_json::Error;
```
Comment (michaelkirk) [inline src/lib.rs:456]: I struggled with the name a little bit. At first I though `JsonError`, but to me that implies only that there was some problem with the Json. However, we also use this to validate geojson schema - e.g. a missing "features" key for a feature collection. It's valid JSON, but not valid GeoJson.

**Review by urschrei — APPROVED** [review]
