### PR TITLE
mismatch type error

### LINKED ISSUE #201: InvalidGeometryConversion should have "expected" vs. "found" types.
Currently when trying to convert from a geojson geometry to an incompatible geo-type (e.g. a Point to a LineString) we use this error:

```
#[error("Encountered a mismatch when converting to a Geo type: `{0}`")]
InvalidGeometryConversion(geojson::Geometry::Value),
```

But instead, I think it'd be more helpful as
```
#[error("Expected geometry type: `{expected_type}`, but found: `{found_type}`")]
InvalidGeometryConversion { expected_type: &'static str, found_type: &'static str }
```

- avoids a very long error message in the case of printing out a large geometry
- it's a more useful error message in my opinion
- no longer requires ownership of the geometry value, paving the way for borrowed geometry conversions

### PR DESCRIPTION
**Pull request by michaelkirk**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

Fixes #201
~~Based on #202, so let's merge that first.~~ merged!

### CODE REVIEW

**Review by metasim — APPROVED** [review]
@michaelkirk Thanks for doing this... glad to get that `clone` out of there!

LGTM.

File: src/geometry.rs [hunk 1]
```diff
@@ -83,21 +83,27 @@ pub enum Value {
     GeometryCollection(Vec<Geometry>),
 }
 
-impl<'a> From<&'a Value> for JsonObject {
-    fn from(value: &'a Value) -> JsonObject {
-        let mut map = JsonObject::new();
-        let ty = String::from(match value {
+impl Value {
+    pub fn type_name(&self) -> &'static str {
```
Comment (metasim) [inline src/geometry.rs:87]: 💯

**Comment by michaelkirk** [comment]
bors r=metasim
